//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSessions
    {
        public int SessionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    
        public virtual UserAccounts UserAccounts { get; set; }
    }
}
